version: '3.4'
services:
  web:
    build: .
    container_name: demo-page
    volumes:
      - .:/home/webuser
      - /home/webuser/node_modules
    ports:
      - '1235:1235'
    command: npm run demo
